language: python
python:
  - "3.6"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
before_script: redis-cli ping
script:
  - nosetests
after_success:
- bash <(curl -s https://codecov.io/bash)
services:
  - redis-server
  - postgresql
